"""empty message

Revision ID: 8a7653bb13bd
Revises: eaa4554ee1c2
Create Date: 2017-11-25 19:21:33.247000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a7653bb13bd'
down_revision = 'eaa4554ee1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ab_permission_view_role')
    op.drop_table('sys_org')
    op.drop_table('booking_ground')
    op.drop_table('sys_role')
    op.drop_table('sys_role_menu')
    op.drop_table('ab_user_role')
    op.drop_table('sys_menu')
    op.drop_table('ab_permission_view')
    op.drop_table('ab_role')
    op.drop_table('ground_occupy')
    op.drop_table('ab_permission')
    op.drop_table('ab_user')
    op.drop_table('ab_register_user')
    op.drop_table('ab_view_menu')
    op.drop_table('booking')
    op.drop_table('sys_grounds')
    op.drop_table('sys_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_account', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_pwd', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user_no', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('position', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('org_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('user_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nation', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('birthday', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('state', mysql.VARCHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sys_grounds',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('config', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('picture', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('org_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('state', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('booking',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('order_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('repeat_book', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('repeat_date', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('start_date', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('end_date', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('start_time', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('end_time', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_view_menu',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_register_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('registration_date', mysql.DATETIME(), nullable=True),
    sa.Column('registration_hash', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('fail_login_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('changed_on', mysql.DATETIME(), nullable=True),
    sa.Column('created_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by_fk', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], name=u'ab_user_ibfk_2'),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], name=u'ab_user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_permission',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ground_occupy',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ground_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('occupy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_permission_view',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('view_menu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], [u'ab_permission.id'], name=u'ab_permission_view_ibfk_1'),
    sa.ForeignKeyConstraint(['view_menu_id'], [u'ab_view_menu.id'], name=u'ab_permission_view_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sys_menu',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('url', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('icon_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('component', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sort_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_user_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'ab_role.id'], name=u'ab_user_role_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'ab_user.id'], name=u'ab_user_role_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sys_role_menu',
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('menu_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sys_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('booking_ground',
    sa.Column('booking_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ground_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('booking_date', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('booking_id', 'ground_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sys_org',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('org_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('org_type', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ab_permission_view_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('permission_view_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_view_id'], [u'ab_permission_view.id'], name=u'ab_permission_view_role_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], [u'ab_role.id'], name=u'ab_permission_view_role_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_account', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_pwd', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('user_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hobby', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('nation', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('birthday', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('changed_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('state', mysql.VARCHAR(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
